nama=(input("Masukan nama Anda :"))
matkul=(input("Masukan nama matakuliah :"))
grup=(input("Masukan grup Anda:"))
print ("Hallo!",nama*2)
print("Anda tergabung dalam kelas",matkul,"pada grup",grup)
